{{- if .Values.ingress.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
spec:
  secretName: {{ .Release.Name }}-crt
  dnsNames:
  - claimcheck.astrify.com
  acme:
    config:
    - http01:
        ingressClass: gce
      domains:
      - claimcheck.astrify.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
{{- end -}}