apiVersion: v1
kind: Service
metadata:
  name: claimcheck-svc
  labels:
    run: claimcheck-svc
spec:
  type: NodePort
  ports:
  - port: 80 # On which port you want to publish the website dep
    targetPort: 1323 # The port exposed by your container
    protocol: TCP
  selector:
    app: {{ template "ui.name" . }}
    release: {{ .Release.Name }}
