apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    run: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }} # On which port you want to publish the website dep
    targetPort: {{ .Values.service.internalPort }} # The port exposed by your container
    protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ template "ui.name" . }}
    release: {{ .Release.Name }}
