stages:
- build
- test
- release
- deploy

services:
- docker:dind

variables:
  CLUSTER_NAME: test-cluster
  ZONE: us-central1-a
  PROJECT: astrify-test-1
  DOMAIN_NAME: claimcheck.astrify.com

  CONTAINER_IMAGE: registry.gitlab.com/astrify/claimcheck
  CONTAINER_IMAGE_BUILT: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375  # required since we use dind

  SERVICE_ACCOUNT: /etc/deploy/sa.json
  PROD_NAMESPACE: default
  PROD_RELEASE_NAME: astrify-prod-claimcheck

test:
  stage: test
  script:
  - exit 0

# build container image
build:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  script:
  - echo "Building Dockerfile-based application..."
  - docker build -t ${CONTAINER_IMAGE_BUILT} .
  - echo $CI_REGISTRY_PASSWORD | docker login --username=$CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - echo "Pushing to the Container Registry..."
  - docker push ${CONTAINER_IMAGE_BUILT}

# tag container image that passed the tests successfully
# and push it to the registry
release:
  stage: release
  image: docker:stable
  services:
  - docker:dind
  script:
  - echo $CI_REGISTRY_PASSWORD | docker login --username=$CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - echo "Pulling docker image from Container Registry"
  - docker pull ${CONTAINER_IMAGE_BUILT}
  - echo "Logging to Container Registry at ${CI_REGISTRY}"
  - echo "Pushing to Container Registry..."
  - docker tag ${CONTAINER_IMAGE_BUILT} ${CONTAINER_IMAGE}:$(cat VERSION)
  - docker push ${CONTAINER_IMAGE}:$(cat VERSION)
  - docker tag ${CONTAINER_IMAGE}:$(cat VERSION) ${CONTAINER_IMAGE_LATEST}
  - docker push ${CONTAINER_IMAGE_LATEST}
  - echo ""
  only:
  - master

# deploy to production environment (manual)
deploy_prod:
  stage: deploy
  image: artemkin/helm-gke:1.0
  before_script:
  - mkdir -p /etc/deploy
  - echo ${service_account} | base64 -d > ${SERVICE_ACCOUNT}
  - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT}
  - gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE} --project ${PROJECT}
  - helm init --client-only
  script:
  - helm upgrade --install
    --set image.tag=$(cat VERSION)
    --wait
    --namespace=${PROD_NAMESPACE}
    ${PROD_RELEASE_NAME} ./charts/claimcheck
  environment:
    name: production
    url: https://${DOMAIN_NAME}
  when: manual
  only:
  - master