# https://gitlab.com/help/ci/docker/using_docker_build.md
# sudo gitlab-runner exec docker --docker-privileged build
image: docker:stable
stages:
- test
- build
- deploy

services:
- docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
- export

test:
  stage: test
  image: golang:1.11
  script:
  - go build ./...
  - go test ./...
  tags:
  - local

build:
  stage: build
  script:
  - echo $CI_JOB_TOKEN | docker login --username=gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
  tags:
  - local

deploy to staging:
  stage: deploy
  script: make deploy
  environment:
    name: claimcheck.staging
    url: https://staging.claimcheck.app/