# https://gitlab.com/help/ci/docker/using_docker_build.md
# sudo gitlab-runner exec docker --docker-privileged build
image: docker:stable
services:
- docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
- export
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
  tags:
  - local