replicaCount: 2
image:
  repository: registry.gitlab.com/astrify/claimcheck
  tag: latest
  pullPolicy: Always

envVars:
  APP_ENV: test

service:
  name: claimcheck
  type: NodePort
  externalPort: 1323
  internalPort: 1323