replicaCount: 2
image:
  repository: registry.gitlab.com/astrify/stellar-claimcheck
  tag: latest
  pullPolicy: Always

envVars:
  APP_ENV: test

service:
  name: claimcheck
  type: NodePort
  externalPort: 1323
  internalPort: 1323

nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

ingress:
  enabled: true
  host: astrify.com
  tls:
    - secretName: claimcheck-tls
      hosts:
        - astrify.com