replicaCount: 2
image:
  repository: registry.gitlab.com/astrify/claimcheck
  tag: latest
  pullPolicy: Always

envVars:
  APP_ENV: test

service:
  name: claimcheck
  type: NodePort
  externalPort: 1323
  internalPort: 1323

imageCredentials:
  name: gitlab-registry-secret
  registry: registry.gitlab.com
  username: user
  password: pass